# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: guillenjeremy26
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: mts-backend-api
# "service" is the name of this project. This will also be added to your AWS resource names.
service: mts-backend-api

useDotenv: true

provider:
  name: aws
  runtime: python3.12
  stage: ${opt:stage, 'local'}
  environment:
    DATABASE_URL: ${env:DATABASE_URL}

plugins:
  - serverless-offline

functions:
  api:

    handler: app/handler_api.router

    events:

      - httpApi:

          path: /{proxy+}

          method: get

      - httpApi:

          path: /{proxy+}

          method: post

      - httpApi:

          path: /{proxy+}

          method: put

      - httpApi:

          path: /{proxy+}

          method: delete
